### ISSUE TITLE
Development workflow question

### ISSUE THREAD

**Issue by johanneswuerbach** [instruqt/skeleton#5]
I'm new to working with instruqt, so maybe I'm misunderstanding the setup or desired workflow, but I wondered if it wouldn't make more sense to commit the dev version of a track by default.

Right now it feels a bit inconvenient that you can't just locally create a new branch and start working as the actions convert step is required.

Couldn't this be solved by generally tracking the dev versions in the repository and only convert & publish the tracks as part of the main branch CI?

This would also prevent accidentally push to a live track when working locally.

Is there anything I'm missing?

**Comment by scarolan** [comment]
Hi @johanneswuerbach - unfortunately there are some limitations and issues with the platform that have made us very hesitant to require users to put dev versions of things into repos.  This would also allow humans to choose the names of their dev tracks which will inevitably lead to a huge mess.  Users are terrible about standards and we currently don't have a way in the platform to clearly mark a track as dev, other than with tags or in the title itself.

The reason we are so prescriptive with this is because we have to support it across many users, many of whom have never really built their own CI/CD platform what to speak of doing with instruqt.  

How would you envision enforcing naming standards when users are simply allowed to create a branch, copy a track and start working on their own?

**Comment by johanneswuerbach** [comment]
> How would you envision enforcing naming standards when users are simply allowed to create a branch, copy a track and start working on their own?

Similar to how this is done today I guess, so fail in CI if the track isn't called `-dev` or prefixed with `DEV`.

> Users are terrible about standards

This is pretty much my concern with the current setup, it is fairly easy to accidentally push a production track, which should never be done manually outside CI.

In any case, this was more an open question, we are currently trialing out this setup and I'm happy to report back our learnings.

**Comment by scarolan** [comment]
Let's continue this discussion in your slack channel, I can arrange a meeting with your CS person.
